### ISSUE TITLE
Weekly schedule not working as expected

### ISSUE THREAD

**Issue by tnorchids** [jgeurts/FluentScheduler#39]
If it is Thursday at 12:40PM and this code is executed,

            Schedule s = this.Schedule(() =>
            {
                // some code to execute
            });
            s.ToRunEvery(1).Weeks().On(DayOfWeek.Thursday).At(12, 45);

shouldn't the task get executed in 5 minutes, at 12:45PM?  This doesn't appear to be happening.

**Comment by ricjac** [comment]
Having the same issue, had to change to 's.ToRunEvery(0).Weeks()' for this to work.
@petergledhill thanks for the work around.
