### ISSUE TITLE
Question on Scheduler with specific start date

### ISSUE THREAD

**Issue by johnkamau** [jgeurts/FluentScheduler#50]
I have a question regarding a schedule that has a specific start date.
For instance if I schedule an action below:

MyRegistry.Schedule(Task).ToRunOnceAt("27/11/2014 11:30").AndEvery(5).Minutes()

Does the above code mean that the scheduler will execute once on that day at 11:30 and every five minutes from then (11:35, 11:40, 11:45 etc), or does it mean it will run once on that start date and every five minutes from when the schedule was created?

I ask because I seem to notice that the code for .OnEvery(x).Minutes() seems to be based off the time the schedule was created as opposed to the date set in the .ToRunOnceAt(xxx) value.

**Comment by jgeurts** [comment]
Yep, it will run at 11:30 and then every 5 minutes from then
