### ISSUE TITLE
Have you considered how FluentScheduler might be used with TopShelf?

### ISSUE THREAD

**Issue by crosswins** [jgeurts/FluentScheduler#51]
I have a TopShelf service but I am not clear on how to integrate FluentScheduler into the service to ensure that although it starts up as a WIndows Service, the actual processing is governed by FluentScheduler.

Thanks, Brian

**Comment by jgeurts** [comment]
Hi Brian,

I haven't used TopShelf, but I'm open to a pull request for sample usage

**Comment by crosswins** [comment]
Hi Jim,

I wasn't able to get this working at the time but I am interested in returning to it in something I am working on at the moment perhaps in the next few weeks.

Best regards

Brian


Sent from my Windows Phone
________________________________
