### ISSUE TITLE
Run a task only within working hours

### ISSUE THREAD

**Issue by mostergaard** [jgeurts/FluentScheduler#53]
Just taking a look at this library, and it looks interesting. One thing, I don't seem to be able to figure out how to do, though, is to run a task every 10 minutes between normal working hours - e.g. between 8:00 and 16:00 Monday to Friday. Is that possible?

I guess I could always do .ToRunEvery(10).Minutes() and then in the task skip it if it's not within the correct time, but that's not so nice.

**Comment by jgeurts** [comment]
Yeah, your best option, in this case, is to do the datetime check in your task
