### ISSUE TITLE
it won't work with nop commerce.

### ISSUE THREAD

**Issue by meitiever** [jgeurts/FluentScheduler#56]
Anyone knows that will this cope with nop commerce?
I have created a nop plugin of task manager.
But the simple task was executed once only.
Please help.
Thanks.

**Comment by geovanimartinez** [comment]
Nop has it's own built in Task Scheduler. When you create a task you can tell it to run at a predefined interval but nothing like ( Monday's at 5:00 PM, Wed at 3:00 PM ). FluentScheduler allows you to define task schedules such as Mon 5:00 PM and Wed at 3:00 PM but to change their execution times you would have to modify the code (unline nop where you can alter the interval value at the db table level). I use FluentScheduler on some project and nop's implementation on others but where I have to allow the end user change or define the schedule I go with quartz .NET http://www.quartz-scheduler.net/ and when a built in scheduler is overkill but yet require to run jobs on defined days and times I use visualCron http://www.visualcron.com/. Hpe my answer helps you out some how.

**Comment by meitiever** [comment]
Got it. thanks.
Yes, nop has its own task manager. but the original one is too simple to use.
i am creating a task manager with capability of creating and running tasks dynamically.
and more over, the platform has to be web based in that many end-users will view running results and reports in his own office. in that case, visualcron is our of consideration.
could quartz-scheduler running based on a web app? i did not see web tester in the solution. thanks.
by the way, my last question is why the fluent scheduler tasks run once only in my nop app? maybe i should paste some source code here for the help.(code snippet will come soon.)
thanks.
